language: python
python:
   - 3.6
# command to install dependencies
before_install:
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/
  - ./configure --prefix=/usr
  - make && sudo make install
  - cd ..
install:
  - pip install -r requirements.txt
  - pip install -U tushare
# command to run tests
script: pytest tests
