FROM python:3.6

WORKDIR /usr/src/app

COPY requirements_backtest.txt ./requirements.txt
RUN pip install --no-cache-dir -U -r requirements.txt
RUN pip install --no-cache-dir tushare

COPY . .

CMD ["python", "./src/program.py"]


