version: '3'

services:
  sut:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "coverage run --source src -m unittest discover -s tests/ -t . && coverage report"
    environment:
      - PYTHONPATH=./src

